# Generated by Django 4.2.3 on 2023-07-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceImages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='ecommerce_imgs')),
            ],
        ),
    ]
